### ISSUE TITLE
Error - Cannot access a disposed object.

### ISSUE THREAD

**Issue by gcamou** [brunohbrito/MongoDB-RepositoryUoWPatterns#2]
Hi my friend, I downloaded your code and it's awesome and run good. but before the post-product; when try to dispose the class. appare a error.

<img width="915" alt="Screenshot at Sep 29 19-25-17" src="https://user-images.githubusercontent.com/3238630/65842139-12ae8880-e2ef-11e9-9f7b-77219b1c6341.png">
<img width="483" alt="Screenshot at Sep 29 19-26-27" src="https://user-images.githubusercontent.com/3238630/65842140-12ae8880-e2ef-11e9-8ec7-d94d2b416d52.png">

**Comment by brunobritodev** [comment]
Hi @gcamou 

Sorry about this error. This dispose was first made to control Session. But After a few updates later I've change how session was built and doesn't make to control Dispose now.

I'll fix asap

**Comment by brunobritodev** [comment]
I made a change, so It'l not happen.

I've also change how MongoDbContext is created to prevent extra memory comsuption.
