### ISSUE TITLE
Atualização no .net core e libs

### ISSUE THREAD

**Issue by felipementel** [brunohbrito/MongoDB-RepositoryUoWPatterns#3]
Gostei bastante da proposta da solução e gostaria de manter seu repositorio atualizado em relação ao .net core e as bibliotecas utilizadas.
Se puder criar uma branch para que eu faça um pull request com esses updates.

Obrigado.

**Comment by brunobritodev** [comment]
Criei uma branch `feature/v3.1`. Pode fazer uma PR.

No fundo acho que vou deixar a master na sua versão e ter uma branch para a v2.1.

Já que 2.1 e 3.1 são LTS.

**Comment by felipementel** [comment]
Grande Bruno, tudo bem?

               Tentei fazer um push para abrir o PR mas to sem acesso.
               Consegue me ajudar?

[cid:image003.jpg@01D687D8.D23E1CE0]


Att,
Felipe Augusto

De: Bruno Brito <notifications@github.com>
Enviada em: Wednesday, September 9, 2020 6:10 AM
Para: brunohbrito/MongoDB-RepositoryUoWPatterns <MongoDB-RepositoryUoWPatterns@noreply.github.com>
Cc: Felipe Augusto <felipementel@hotmail.com>; Author <author@noreply.github.com>
Assunto: Re: [brunohbrito/MongoDB-RepositoryUoWPatterns] Atualização no .net core e libs (#3)


Criei uma branch feature/v3.1. Pode fazer uma PR.

No fundo acho que vou deixar a master na sua versão e ter uma branch para a v2.1.

Já que 2.1 e 3.1 são LTS.

**Comment by brunobritodev** [comment]
Merged PR #4
